# Generated by Django 3.0.2 on 2020-02-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_status', models.CharField(choices=[('a', 'Active'), ('d', 'De-active')], max_length=1, verbose_name='Activity status')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='states', to='company.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ('name', 'activity_status'),
            },
        ),
    ]
