# Generated by Django 3.0.2 on 2020-02-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_status', models.CharField(choices=[('a', 'Active'), ('d', 'De-active')], max_length=1, verbose_name='Activity status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('device_id', models.BigIntegerField(verbose_name='Device ID')),
                ('os_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='OS Version')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('sim_card', models.PositiveIntegerField(verbose_name='SIM card Number')),
                ('sensor_count', models.PositiveIntegerField(verbose_name='Sensor count')),
            ],
            options={
                'verbose_name': 'Hardware',
                'verbose_name_plural': 'Hardware',
                'ordering': ('title', 'device_id'),
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_status', models.CharField(choices=[('a', 'Active'), ('d', 'De-active')], max_length=1, verbose_name='Activity status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
            },
        ),
    ]
