# Generated by Django 3.0.2 on 2020-02-08 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_status', models.CharField(choices=[('a', 'Active'), ('d', 'De-active')], max_length=1, verbose_name='Activity status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_status', models.CharField(choices=[('a', 'Active'), ('d', 'De-active')], max_length=1, verbose_name='Activity status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('icon', models.CharField(max_length=30, verbose_name='Icon')),
                ('color', models.CharField(max_length=6, verbose_name='Color')),
                ('marker_shape', models.CharField(choices=[('cr', 'Circle'), ('sq', 'Square'), ('st', 'Star'), ('pg', 'Polygon')], max_length=2)),
            ],
            options={
                'verbose_name': 'Figure',
                'verbose_name_plural': 'Figures',
                'ordering': ('title', 'activity_status'),
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_status', models.CharField(choices=[('a', 'Active'), ('d', 'De-active')], max_length=1, verbose_name='Activity status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='Layer')),
                ('features', models.ManyToManyField(blank=True, related_name='layer_features', to='layer.Feature', verbose_name='Features')),
            ],
            options={
                'verbose_name': 'Layer',
                'verbose_name_plural': 'Layers',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=16)),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('figure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pois', to='layer.Figure', verbose_name='Figure')),
                ('layer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pois', to='layer.Layer', verbose_name='Layer')),
            ],
            options={
                'verbose_name': 'Point of interest',
                'verbose_name_plural': 'Points of interest',
                'ordering': ('title',),
            },
        ),
    ]
