# Generated by Django 3.0.2 on 2020-02-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_status', models.CharField(choices=[('a', 'Active'), ('d', 'De-active')], max_length=1, verbose_name='Activity status')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ('name',),
            },
        ),
    ]
