# Generated by Django 3.0.2 on 2020-02-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layer', '0001_initial'),
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=35, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last name')),
                ('nid', models.CharField(blank=True, max_length=10, null=True, verbose_name='National code')),
                ('tel', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tel')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='VehicleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_status', models.CharField(choices=[('a', 'Active'), ('d', 'De-active')], max_length=1, verbose_name='Activity status')),
                ('group_name', models.CharField(max_length=100, unique=True, verbose_name='Group name')),
            ],
            options={
                'verbose_name': 'Vehicle group',
                'verbose_name_plural': 'Vehicle groups',
                'ordering': ('group_name', 'activity_status'),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_status', models.CharField(choices=[('a', 'Active'), ('d', 'De-active')], max_length=1, verbose_name='Activity status')),
                ('title', models.CharField(blank=True, max_length=70, null=True, verbose_name='Title')),
                ('number_plate', models.CharField(max_length=8, verbose_name='Number plate')),
                ('service_status', models.CharField(choices=[('ons', 'On service'), ('ofs', 'Out of service')], max_length=3, verbose_name='Service status')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='driving.Driver', verbose_name='Driver')),
                ('figure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='layer.Figure', verbose_name='Figure')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='zone.State', verbose_name='State')),
                ('vehicle_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='driving.VehicleGroup', verbose_name='Vehicle group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
