# Generated by Django 3.0.2 on 2020-02-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving', '0002_auto_20200210_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(max_length=35, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last name'),
        ),
    ]
